[package]
name = "adventofcode_2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4" # day 6
pathfinding = "3.0.5" # day 15
